name: Build & Deploy Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout source
      uses: actions/checkout@v4

    - name: 🐳 Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 📦 Get version from package.json
      id: package-version
      run: echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT

    - name: 🛠️ Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          calypso666/waktusolat.me:${{ steps.package-version.outputs.version }}
          calypso666/waktusolat.me:latest

    - name: 🚀 Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/own
          docker compose down waktusolat.me || true
          docker compose down waktusolat.me-staging || true
          docker pull calypso666/waktusolat.me:latest
          docker compose up -d waktusolat.me
